# Generated by Django 2.2.10 on 2021-02-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PollPossibleAnswers',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('date_start', models.DateField(editable=False)),
                ('date_end', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('type', models.CharField(max_length=1)),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Polls')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(editable=False)),
                ('text_ans', models.TextField(editable=False, null=True)),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Questions')),
                ('user_ans', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.PollPossibleAnswers')),
            ],
        ),
        migrations.AddField(
            model_name='pollpossibleanswers',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='polls.Questions'),
        ),
    ]
