# Generated by Django 2.2.10 on 2021-02-25 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollpossibleanswers',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Questions'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='poll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Polls'),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='q_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Questions'),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='user_ans',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.PollPossibleAnswers'),
        ),
    ]
